name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev
      - release

env:
  DOCKER_REGISTRY: registry.local
  DOCKER_IMAGE: mockplant
  DOCKER_TAG: latest

jobs:
  build:
    name: Build Docker Image and Upload
    runs-on: ubuntu-latest

    steps:
      
      - name: Adding NeoDNS Server
        run: |
          echo "nameserver 10.60.1.2" > /etc/resolv.conf
          echo "nameserver 8.8.8.8" >> /etc/resolv.conf          

      - name: Set up environment and install required packages
        run: |
          apt update
          apt install -y git docker.io jq curl iputils-ping 

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_TAG} .

      - name: Push Docker Image
        run: |
          docker push ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_TAG}

      - name: Pull Image to Verify
        run: |
          docker pull ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_TAG}

      - name: Cleanup Docker
        if: always()
        run: |
          docker system prune -af || true